#debug: true

logging.level.org.hibernate.type.descriptor.sql.BasicBinder: trace

spring:
  jpa:
    open-in-view: false
    properties:
      hibernate.format_sql: true

slack:
  hook-url:
    semicolon: ${hook-url.semicolon}
