main-jpa:
  datasource:
    driver-class-name: ${datasources.maindb.driver-class-name}
    url: ${datasources.maindb.url}
    username: ${datasources.maindb.username}
    password: ${datasources.maindb.password}
  dialect: ${datasources.maindb.dialect}
  entity-package: com.baegoon.domain.main
  ddl-auto: create
