main-jpa:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:maindb;MODE=MySQL;DB_CLOSE_DELAY=-1
    username: sa
    password:
  dialect: org.hibernate.dialect.H2Dialect
  persistence-unit: main
  entity-package: com.baegoon.domain.main
  ddl-auto: create
