debug: true

spring:
  profiles:
    include: domain
  jpa:
    properties:
      hibernate:
        format_sql: true

grpc:
  port: 1234

logging:
  level:
    org.hibernate.type.descriptor.sql.BasicBinder: trace
