multiple-datasources:
  default:
    driver-class-name: org.h2.Driver
    jdbc-url: jdbc:h2:mem:default;MODE=MySQL;DB_CLOSE_DELAY=-1
    username: sa
    password:
    dialect: org.hibernate.dialect.H2Dialect
    persistence-unit: main
    entity-package: com.baegoon.domain
    ddl-auto: create
