sub-jpa:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/subdb?useSSL=false
    username: root
    password: password
  dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  entity-package: com.baegoon.domain.sub
  ddl-auto: create
