sub-jpa:
  datasource:
    driver-class-name: ${datasources.subdb.driver-class-name}
    url: ${datasources.subdb.url}
    username: ${datasources.subdb.username}
    password: ${datasources.subdb.password}
  dialect: ${datasources.subdb.dialect}
  ddl-auto: create
